### ISSUE TITLE
Can't install version 2.1.3 on MacOS 12.6 Monterey with ARM Apple Silicon

### ISSUE THREAD

**Issue by nicmarti** [pganalyze/pg_query#255] opened 2022-09-15 09:05 UTC
pg_query version 2.1.3 won't install on MacOS 12.6 Monterey with an arm64 Ruby 3.1.2

Here is the error message extracted from a `bundle install` 

```linking shared-object pg_query/pg_query.bundle
Undefined symbols for architecture arm64:
  "Init_pg_query", referenced from:
     -exported_symbol[s_list] command line option
     (maybe you meant: _Init_pg_query)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [pg_query.bundle] Error 1

make failed, exit code 2
```

More details about the environment : 
```
ruby -v
  ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]

bundler --version
  Bundler version 2.2.32
```

Also if I try to run a `make` from the .rbenv folder =>

```
cd $HOME/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/pg_query-512169280fea/ext/pg_query

➜  pg_query git:(main) ✗ make
linking shared-object pg_query/pg_query.bundle
Undefined symbols for architecture arm64:
  "Init_pg_query", referenced from:
     -exported_symbol[s_list] command line option
     (maybe you meant: _Init_pg_query)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [pg_query.bundle] Error 1
```

Any help or ideas are welcome

**Comment by nicmarti** [comment] 2022-09-15 11:15
I found one of my colluegue that has the same architecture/same os but for which it did work. 
Here is a diff on the `Makefile` (note: I filtered the path so that the diffs is showing only what is different) 

On the left : this Makefile compiles on my machine, on the right (pg_query_nic) is the one that does not work

```➜  pg_query diff Makefile ../pg_query_nic/Makefile
35,36c35,36
< sitearchdir = $(DESTDIR)./.gem.20220711-23629-tjpu0c
< sitelibdir = $(DESTDIR)./.gem.20220711-23629-tjpu0c
---
> sitearchdir = $(DESTDIR)./.gem.20220915-29713-qlv927
> sitelibdir = $(DESTDIR)./.gem.20220915-29713-qlv927
94c94
< dldflags = -L/Users/nmartignole/.rbenv/versions/3.1.2/lib  -Wl,-undefined,dynamic_lookup -Wl,-multiply_defined,suppress -Wl,-exported_symbols_list /Users/nmartignole/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/pg_query-512169280fea/ext/pg_query/pg_query_ruby.sym 
---
> dldflags = -L/Users/nmartignole/.rbenv/versions/3.1.2/lib  -Wl,-multiply_defined,suppress -Wl,-exported_symbols_list /Users/nmartignole/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/pg_query-512169280fea/ext/pg_query/pg_query_ruby.sym 
119,120c119,120
< MAKEDIRS = mkdir -p
< INSTALL = /usr/bin/install -c
---
> MAKEDIRS = /usr/local/bin/gmkdir -p
> INSTALL = /usr/local/bin/ginstall -c```

**Comment by nicmarti** [comment] 2022-09-15 11:29
I see that `-undefined,dynamic_lookup` is missing on the version that does not compile.

**Comment by mgallagher0** [comment] 2022-09-15 19:39
I've been having this same issue, I can install version 1.3.0 but not 2.1.3.

**Comment by stanhu** [comment] 2022-09-16 01:02
See https://bugs.ruby-lang.org/issues/19005 for a workaround.

**Comment by stanhu** [comment] 2022-09-16 01:04
This makes me wonder if the visibility hiding in https://github.com/pganalyze/pg_query/blob/e35800c29f3a9a06ffe5bd2d54d67923a4390c79/ext/pg_query/pg_query_ruby.c#L17 is needed.

**Comment by stanhu** [comment] 2022-09-16 01:34
I've confirmed that reverting https://github.com/pganalyze/pg_query/pull/232 works on macOS. In Linux, `-undefined,dynamic_lookup` is the default, but it's not always available on macOS and other platforms.

**Comment by stanhu** [comment] 2022-09-16 04:43
https://github.com/pganalyze/pg_query/pull/256 fixes this issue.

**Comment by namrata-vts** [comment] 2022-09-16 05:59
> https://bugs.ruby-lang.org/issues/19005

I can workaround the problem by doing:

gem install pg_query -- --with-ldflags="-Wl,-undefined,dynamic_lookup"

**Comment by stanhu** [comment] 2022-09-17 04:22
It looks like there is an upstream Ruby fix for this problem: https://github.com/ruby/ruby/commit/6898984f1cd1b0375c3da44d7832724489e0e470

It'd be nice if this were backported.

**Closed** 2022-09-17 08:45 UTC

**Comment by nicmarti** [comment] 2022-09-19 07:38
Thanks for the quick fix

**Comment by asadakbar** [comment] 2022-10-20 15:55
Leaving this for anyone else that hits this issue - I couldn't update my pg_query version so downgrading the Xcode version from 14 to 13 fixed this issue for me.

**Comment by lfittl** [comment] 2022-10-21 05:11
@asadakbar Thanks for adding the note - curious what was challenging about updating your pg_query version? (maybe another gem requiring a different protobuf gem version?)
