### ISSUE TITLE
Deparsing ignores database selection

### ISSUE THREAD

**Issue by skpravien** [pganalyze/pg_query#288] opened 2023-05-30 11:13 UTC
If the query is `SELECT * FROM database1.table1;`, after using deparse, this is the output given `SELECT * FROM \"table1\"` . Is there any workaround to include database name in the deparsed query? TIA

**Comment by lfittl** [comment] 2023-06-06 00:18
Thanks for the report, however I cannot reproduce this on the latest version:

```
irb(main):001:0> q = PgQuery.parse("SELECT * FROM database1.table1")
=> #<PgQuery::ParserResult:0x00000001444ba560 @query="SELECT * FROM database1.table1", @tree=<PgQuery::ParseResult: version: 150001, stmts: [<PgQuery::RawStmt: stmt: <PgQuery::Node: select_stmt: <PgQuery::SelectStmt: distinct_clause: [], target_list: [<PgQuery::Node: res_target:...
irb(main):002:0> q.deparse
=> "SELECT * FROM database1.table1"
```

What commands are you running / which version are you testing where you're seeing this?

**Comment by skpravien** [comment] 2023-06-06 04:40
It's very old version. "0.11.2"

**Comment by lfittl** [comment] 2023-06-06 23:01
@skpravien Thanks for checking - I would recommend upgrading then, as this is working as expected in current versions.

I'll close this for now, but please feel free to let us know if you see this issue in a current release as well.

**Closed by lfittl** 2023-06-06 23:01 UTC
