### ISSUE TITLE
Build failed on MacOS with asdf

### ISSUE THREAD

**Issue by imcvampire** [pganalyze/pg_query#167] opened 2020-03-13 15:20 UTC
If I install, build and run on MacOS with `asdf-vm` (a version manager), I face an error when start rails

```
Uncaught exception: dlopen(/Users/.../.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/pg_query-1.2.0/lib/pg_query/pg_query.bundle, 9): no suitable image found.  Did find:
	/Users/.../.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/pg_query-1.2.0/lib/pg_query/pg_query.bundle: mach-o, but built for simulator (not macOS)
```

**Comment by lfittl** [comment] 2021-03-18 23:00
@imcvampire Hmm, I can't reproduce this here (`rbenv` on MacOS)

Do you see the same problem in the new 2.0 release?

**Comment by lfittl** [comment] 2021-07-04 21:49
Closing this since no further updates - please let me know if this is still an issue on the most recent release.

**Closed by lfittl** 2021-07-04 21:49 UTC
